name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Check running containers
        run: docker ps
      
      - name: Test application
        run: |
          # Wait for applications to start
          sleep 10
          # Add your test commands here
          # For example: curl http://localhost:8080
      
      - name: Stop containers
        if: always()
        run: docker-compose down
